spring:
  application:
    name: cursos-service
  database:
    driverClassName:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/edutech
    username: root
    password: demo
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true